const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const state={identity:null,style:null,preferences:null,telegram:null,mobile:null,runtime:{},conversationId:localStorage.getItem('eirven_conversation')||null,job:null,view:'home',runtimeAction:{},chatBusy:false,chatController:null,chatCancelled:false,chatTimedOut:false,chatPending:null};
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok){let t=await r.text();try{t=JSON.parse(t).detail||t}catch{}throw new Error(t||`HTTP ${r.status}`)}const ct=r.headers.get('content-type')||'';return ct.includes('application/json')?r.json():r.text()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function configuredName(){return String(state.identity?.assistant_name||'Эйрвен').trim()||'Эйрвен'}
function wakeName(r=state.runtime){return String(r?.wake_phrase||configuredName()).trim()||configuredName()}
function applyAssistantName(raw){const name=String(raw||'Эйрвен').trim()||'Эйрвен';document.title=name;$$('.assistant-name-ref').forEach(el=>el.textContent=name);$('#stage-title').textContent=state.view==='home'?name:$('#stage-title').textContent;$('.brand-orb').title=name;$('.brand-orb').setAttribute('aria-label',name);$('#main-orb').setAttribute('aria-label',`Сфера ${name}`);$('#message-input').placeholder=`Напиши ${name}…`;$('#home-wake-name').textContent=name;$('#onboard-wake-name').textContent=name;$('#onboard-intro-name').textContent=name}
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#stage-title').textContent=name==='home'?(state.identity?.assistant_name||'Эйрвен'):{tasks:'Задачи',settings:'Настройки'}[name]||'Эйрвен';if(name==='tasks')loadTasks();if(name==='settings')loadPreferences()}
function openSettingsTab(tab='general'){setView('settings');const button=$(`[data-settings-tab="${tab}"]`);if(button)setTimeout(()=>button.click(),0)}
function applyAgentRoute(route={}){if(route.open_settings_tab)openSettingsTab(route.open_settings_tab)}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
function addMessage(role,text,extra=''){const box=$('#messages'),node=document.createElement('div');node.className=`message ${role} ${extra}`;node.textContent=text;box.append(node);box.scrollTop=box.scrollHeight;return node}
async function ensureConversation(force=false){if(state.conversationId&&!force)return state.conversationId;const conv=await api('/api/conversations',{method:'POST',body:JSON.stringify({title:configuredName(),mode:'Друг'})});state.conversationId=conv.id;localStorage.setItem('eirven_conversation',state.conversationId);return state.conversationId}
async function loadHistory(){if(!state.conversationId)return;try{const conv=await api(`/api/conversations/${state.conversationId}`);$('#messages').innerHTML='';(conv.messages||[]).slice(-50).forEach(m=>addMessage(m.role==='user'?'user':'assistant',m.content||''))}catch{state.conversationId=null;localStorage.removeItem('eirven_conversation')}}
function autosize(){const input=$('#message-input');input.style.height='auto';input.style.height=`${Math.min(180,Math.max(76,input.scrollHeight))}px`}
function setChatBusy(busy){state.chatBusy=busy;const button=$('#send-message');button.textContent=busy?'Остановить':'Отправить';button.setAttribute('aria-label',busy?'Остановить ответ':'Отправить');button.classList.toggle('danger-soft',busy)}
function consumeStreamPacket(packet,node,current){let full=current;for(const line of packet.split('\n')){if(!line.startsWith('data:'))continue;let event;try{event=JSON.parse(line.slice(5).trim())}catch{continue}if(event.type==='token'){full=event.full||full+(event.content||'');node.textContent=full;node.classList.remove('pending')}else if(event.type==='error')throw new Error(event.message||'Не удалось получить ответ');else if(event.type==='done'){full=event.answer||full;node.textContent=full||'Готово.';node.classList.remove('pending');applyAgentRoute(event.route||{})}}return full}
async function streamChat(payload,node,controller){let inactivity=0;const arm=()=>{clearTimeout(inactivity);inactivity=setTimeout(()=>{state.chatTimedOut=true;controller.abort()},60000)};arm();try{const response=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});if(!response.ok)throw new Error((await response.text())||`HTTP ${response.status}`);if(!response.body)throw new Error('Поток ответа недоступен');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',full='';for(;;){const {value,done}=await reader.read();if(done)break;arm();buffer+=decoder.decode(value,{stream:true});let split;while((split=buffer.indexOf('\n\n'))>=0){full=consumeStreamPacket(buffer.slice(0,split),node,full);buffer=buffer.slice(split+2)}}buffer+=decoder.decode();if(buffer.trim())full=consumeStreamPacket(buffer,node,full);node.classList.remove('pending');return full}finally{clearTimeout(inactivity)}}
async function stopChat(){if(!state.chatBusy)return;state.chatCancelled=true;state.chatController?.abort();const id=state.conversationId;if(id){try{await api(`/api/chat/${encodeURIComponent(id)}/stop`,{method:'POST'})}catch{}}}
async function sendMessage(){if(state.chatBusy){await stopChat();return}const input=$('#message-input'),message=input.value.trim();if(!message)return;const controller=new AbortController();state.chatController=controller;state.chatCancelled=false;state.chatTimedOut=false;setChatBusy(true);let pending=null;let slow=0;try{await ensureConversation();input.value='';autosize();addMessage('user',message);pending=addMessage('assistant','Думаю…','pending');state.chatPending=pending;slow=setTimeout(()=>{if(state.chatBusy&&pending.classList.contains('pending'))pending.textContent='Это занимает дольше обычного. Я всё ещё работаю — ответ можно остановить.'},8000);await streamChat({message,conversation_id:state.conversationId,mode:'Друг',model:'auto',attachment_ids:[]},pending,controller)}catch(e){if(!pending)pending=addMessage('assistant','','pending');pending.classList.remove('pending');if(state.chatCancelled)pending.textContent='Ответ остановлен.';else if(state.chatTimedOut||e?.name==='AbortError')pending.textContent='Компьютер слишком долго не отвечал. Проверь модель или повтори команду.';else pending.textContent=`Не получилось ответить: ${e.message}`}finally{clearTimeout(slow);if(state.chatController===controller)state.chatController=null;state.chatPending=null;setChatBusy(false)}}
$('#send-message').onclick=sendMessage;$('#message-input').addEventListener('input',autosize);$('#message-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});$('#new-chat').onclick=async()=>{if(state.chatBusy)await stopChat();state.conversationId=null;localStorage.removeItem('eirven_conversation');$('#messages').innerHTML='';await ensureConversation(true)};

function runtimeLabel(r){if(r.onboarding_complete===false||r.state==='onboarding')return 'знакомлюсь с тобой';if(r.error)return 'микрофон недоступен';if(r.state==='warming'||r.interactive_ready===false)return 'запускаюсь';if(r.speaking)return 'говорю';if(r.state==='hearing')return 'слушаю';if(r.state==='recognizing')return 'понимаю';if(r.state==='thinking')return 'думаю';if(r.state==='armed'||r.session_active)return 'слушаю — говори';return `скажи «${wakeName(r)}»`}
function updateOrb(r){const orb=$('#main-orb');['active','hearing','speaking','thinking','onboarding','mood-happy','mood-sad','mood-curious','mood-tired','mood-warm'].forEach(c=>orb.classList.remove(c));if(r.onboarding_complete===false||r.state==='onboarding')orb.classList.add('onboarding');if(r.session_active||r.state==='armed')orb.classList.add('active');if(r.state==='hearing'||r.state==='recognizing')orb.classList.add('hearing');if(r.state==='thinking')orb.classList.add('thinking');if(r.speaking)orb.classList.add('speaking');const emotion=String(r.speaking_emotion||r.response_emotion||r.mood?.emotion||'').toLowerCase(),mood=emotion==='amused'||emotion==='proud'||emotion==='energetic'?'happy':emotion==='empathetic'||emotion==='calm'?'warm':emotion;if(['happy','sad','curious','tired','warm'].includes(mood))orb.classList.add(`mood-${mood}`);const level=Math.min(.22,Number(r.input_level)||0),speech=Math.max(0,Math.min(1,Number(r.speech_level)||0));document.documentElement.style.setProperty('--voice-level',String(level));document.documentElement.style.setProperty('--speech-level',String(speech));document.documentElement.style.setProperty('--arm',String(Math.max(0,Math.min(1,(Number(r.session_seconds_remaining)||0)/5))))}
async function pollRuntime(){try{const r=await api('/api/voice/runtime');state.runtime=r;updateOrb(r);const wake=wakeName(r);$('#home-wake-name').textContent=wake;$('#onboard-wake-name').textContent=wake;const label=runtimeLabel(r);$('#voice-state').textContent=label;$('#heard-text').textContent=['hearing','recognizing','thinking'].includes(r.state)?(r.last_text||''):'';const chip=$('#runtime-chip');chip.className='runtime-chip '+(r.error?'error':(r.speaking||r.session_active||['hearing','recognizing','thinking','armed'].includes(r.state))?'active':r.running?'live':'');chip.querySelector('b').textContent=label;$('#health-dot').className='health-dot '+(r.running&&!r.error?'ok':'bad')}catch{$('#health-dot').className='health-dot bad'}}
setInterval(pollRuntime,150);pollRuntime();

function humanActivity(rt){if(!rt||!rt.cancellable)return'';let step=String(rt.step||rt.action||'').trim(),goal=String(rt.goal||'').trim();if(step&&!["готово","idle","остановлено"].includes(step.toLowerCase()))return step.replace(/\.$/,'')+'…';if(goal)return 'Занимаюсь: '+goal.slice(0,90)+(goal.length>90?'…':'');return''}
async function pollAction(){try{const rt=await api('/api/runtime');state.runtimeAction=rt;const text=humanActivity(rt),el=$('#activity-caption');el.textContent=text;el.classList.toggle('visible',!!text)}catch{}}
setInterval(pollAction,500);pollAction();

const STYLE_PRESETS={balanced:{directness:4,humor:'сдержанный живой тон, почти без шуток',emotional_support:true,answer_length:'средняя',custom_rules:'Говори естественно, спокойно и по-человечески. Без канцелярита, без лишнего пафоса. Подстраивай тон под ситуацию.'},friendly:{directness:3,humor:'тёплый дружеский юмор, лёгкий и мягкий',emotional_support:true,answer_length:'средняя',custom_rules:'Говори теплее, мягче и поддерживающе. Чаще используй дружелюбные формулировки и живые человеческие реплики.'},brief:{directness:5,humor:'без юмора',emotional_support:false,answer_length:'короткая',custom_rules:'Отвечай коротко, собранно и по делу. Не растекайся мыслью, не добавляй шутки, не проговаривай очевидное.'},free:{directness:4,humor:'заметный живой юмор, игривый, лёгкий, уместный',emotional_support:true,answer_length:'средняя',custom_rules:'Говори свободнее и живее. Допускай короткие уместные шутки, дружеские подколы и более эмоциональные формулировки, но без клоунады.'}};
function presetFromStyle(st){const h=String(st?.humor||'');if(st?.answer_length==='короткая'||Number(st?.directness)>=5)return'brief';if(h.includes('игрив'))return'free';if(h.includes('друж'))return'friendly';return'balanced'}
function setPresetButtons(root,value){if(!root)return;root.querySelectorAll('[data-style-preset]').forEach(button=>button.classList.toggle('active',button.dataset.stylePreset===value))}
async function saveStylePreset(name){const current=await api('/api/style');const patch=STYLE_PRESETS[name]||STYLE_PRESETS.balanced;state.style=await api('/api/style',{method:'PUT',body:JSON.stringify({...current,...patch,assistant_name:state.identity?.assistant_name||current.assistant_name,owner_name:state.identity?.user_address||current.owner_name})});setPresetButtons($('#communication-style'),name);setPresetButtons($('#onboard-style'),name);onboardingDraft.style=name}
async function loadIdentity(){const id=await api('/api/identity');state.identity=id;$('#assistant-name').value=id.assistant_name||'Эйрвен';$('#user-address').value=id.user_address||'';$('#onboard-assistant-name').value=id.assistant_name||'Эйрвен';$('#onboard-user-name').value=id.user_address||'';applyAssistantName(id.assistant_name);return id}
async function saveIdentity(patch){const id=await api('/api/identity',{method:'PUT',body:JSON.stringify(patch)});state.identity=id;await loadIdentity();return id}
async function loadStyle(){try{state.style=await api('/api/style');const preset=presetFromStyle(state.style);setPresetButtons($('#communication-style'),preset);setPresetButtons($('#onboard-style'),preset);onboardingDraft.style=preset}catch{}}
$('#assistant-name').addEventListener('change',e=>saveIdentity({assistant_name:e.target.value}));$('#user-address').addEventListener('change',e=>saveIdentity({user_address:e.target.value}));$$('#communication-style [data-style-preset]').forEach(button=>button.addEventListener('click',()=>saveStylePreset(button.dataset.stylePreset)));$$('#onboard-style [data-style-preset]').forEach(button=>button.addEventListener('click',()=>{onboardingDraft.style=button.dataset.stylePreset;setPresetButtons($('#onboard-style'),onboardingDraft.style)}));

function applyAppearance(p={}){document.body.classList.toggle('sphere-motion-off',p.sphere_motion===false);document.body.classList.toggle('desktop-eyes-off',p.desktop_eyes_enabled===false);document.body.classList.remove('sphere-soft','sphere-balanced','sphere-vivid');document.body.classList.add(`sphere-${p.sphere_intensity||'vivid'}`)}
async function loadPreferences(){try{const p=await api('/api/preferences');state.preferences=p;$('#voice-output-volume').value=Math.round(Number(p.voice_output_volume??.82)*100);$('#voice-output-volume-value').textContent=`${$('#voice-output-volume').value}%`;$('#ui-language').value=p.language||'ru';$('#autostart-enabled').checked=!!p.autostart;$('#notifications-enabled').checked=p.notifications_enabled!==false;$('#mini-mode-enabled').checked=p.mini_mode!==false;$('#sphere-motion').checked=p.sphere_motion!==false;$('#sphere-intensity').value=p.sphere_intensity||'vivid';$('#desktop-comments-enabled').checked=p.desktop_comments_enabled!==false;$('#desktop-eyes-enabled').checked=p.desktop_eyes_enabled!==false;$('#update-channel').value=p.update_channel||'stable';$('#auto-update-check').checked=p.auto_update_check!==false;$('#version-caption').textContent=`EIRVEN ${p.version||'1.7.3'} · ${p.build||'r37-mobile-clean'}`;$('#version-pill').textContent=p.build||'r37-mobile-clean';applyAppearance(p);return p}catch(e){return null}}
async function savePreferences(patch){try{const p=await api('/api/preferences',{method:'PUT',body:JSON.stringify(patch)});state.preferences=p;applyAppearance(p);return p}catch(e){addMessage('assistant',`Настройки: ${e.message}`);throw e}}
$$('[data-settings-tab]').forEach(b=>b.onclick=()=>{$$('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-settings-panel]').forEach(x=>x.classList.toggle('active',x.dataset.settingsPanel===b.dataset.settingsTab));if(b.dataset.settingsTab==='updates'&&state.preferences?.auto_update_check)checkUpdates(false);if(b.dataset.settingsTab==='telegram')loadTelegram();if(b.dataset.settingsTab==='video')loadVideo();if(b.dataset.settingsTab==='mobile')loadMobile()});
function renderMobileQr(url){const box=$('#mobile-download-qr'),link=$('#mobile-download-link'),detail=$('#mobile-apk-detail');box.innerHTML='';link.hidden=true;link.removeAttribute('href');if(!url){box.innerHTML='<span>QR пока недоступен</span>';detail.textContent='APK или Wi‑Fi адрес не найден. Перезапусти EIRVEN после подключения к домашней сети.';return false}try{if(typeof qrcode!=='function')throw new Error('QR-модуль не загрузился');const qr=qrcode(0,'M');qr.addData(url,'Byte');qr.make();box.innerHTML=qr.createSvgTag({cellSize:5,margin:20,scalable:true,title:'Установить EIRVEN Mobile',alt:'QR-код страницы установки'});link.href=url;link.hidden=false;detail.textContent='На телефоне сначала появится подтверждение связи с компьютером, затем кнопка скачивания APK.';return true}catch(e){box.innerHTML='<span>Не удалось создать QR</span>';link.href=url;link.hidden=false;detail.textContent=`QR: ${e.message}. Используй кнопку открытия страницы.`;return false}}
function mobileOptionLabel(option){const kind={wifi:'Wi‑Fi',ethernet:'Кабель',virtual:'VPN/виртуальная',network:'Сеть'}[option.kind]||'Сеть';return `${kind} · ${option.interface||option.ip||''} · ${option.ip||''}`}
function renderMobileNetworkDetail(value,selected){const detail=$('#mobile-network-detail'),option=(value.address_options||[]).find(item=>item.url===selected),virtualWarning=option?.kind==='virtual'?' Кроме того, выбран адрес VPN/виртуальной сети — телефон обычно его не видит. Выбери Wi‑Fi ниже.':'';detail.className='mobile-network-detail';if(value.firewall_ready===false){detail.classList.add('error');detail.textContent=(value.detail||'Windows Firewall не разрешил вход с телефона. Перезапусти EIRVEN через ярлык и подтверди UAC.')+virtualWarning;return}if(value.firewall_ready==null){detail.classList.add('error');detail.textContent=(value.detail||'Не удалось подтвердить правило Windows Firewall. Перезапусти EIRVEN через ярлык.')+virtualWarning;return}if(option?.kind==='virtual'){detail.classList.add('error');detail.textContent='Выбран адрес VPN/виртуальной сети — телефон обычно его не видит. Выбери кнопку Wi‑Fi ниже.';return}detail.classList.add('ready');const adapter=option?.interface?`Выбран интерфейс «${option.interface}» (${option.ip}). `:'';detail.textContent=adapter+(value.detail||'Доступ разрешён только устройствам этого локального сегмента.')}
function chooseMobileAddress(url){const value=state.mobile||{},selected=String(url||'');$('#mobile-address').textContent=selected||'Адрес локальной сети не найден';$$('.mobile-address-option').forEach(button=>button.classList.toggle('active',button.dataset.url===selected));const qrReady=renderMobileQr(selected&&value.apk_available?`${selected}/mobile/install`:'');renderMobileNetworkDetail(value,selected);return qrReady}
function renderMobileAddressOptions(value){const box=$('#mobile-address-options'),options=Array.isArray(value.address_options)?value.address_options:[];box.innerHTML='';box.hidden=options.length<2;for(const option of options){const button=document.createElement('button');button.type='button';button.className=`mobile-address-option ${option.kind==='virtual'?'virtual':''}`;button.dataset.url=option.url;button.textContent=mobileOptionLabel(option);button.title=option.warning||`Использовать ${option.url}`;button.onclick=()=>{const ready=chooseMobileAddress(option.url);$('#mobile-status').textContent=ready?'QR обновлён для выбранного адреса. Попробуй открыть его камерой телефона.':'Адрес выбран, но QR не создался — используй ссылку.'};box.append(button)}}
async function loadMobile(){const status=$('#mobile-status');status.textContent='Проверяю локальную сеть…';try{const value=await api('/api/mobile/config');state.mobile=value;$('#mobile-token').textContent=value.token||'—';renderMobileAddressOptions(value);const selected=value.preferred_address||'';const qrReady=chooseMobileAddress(selected);const preferred=(value.address_options||[]).find(item=>item.url===selected);status.textContent=!value.lan_enabled?'Доступ с телефона выключен в .env':!value.apk_available?'APK не включён в эту сборку':value.firewall_ready===false?'Телефон блокирует Windows Firewall. Перезапусти EIRVEN через ярлык и подтверди UAC.':value.firewall_ready==null?'Не удалось проверить Windows Firewall. Перезапусти EIRVEN через ярлык.':preferred?.kind==='virtual'?'Нашла только виртуальный/VPN-адрес. Отключи VPN или выбери Wi‑Fi адрес ниже.':selected?(qrReady?'Готово: Wi‑Fi адрес проверен, отсканируй QR':'Адрес готов; скачай APK кнопкой'):'Не нашла Wi‑Fi адрес. Подключи компьютер к сети и нажми «Обновить Wi‑Fi адрес».';return value}catch(e){state.mobile=null;renderMobileQr('');$('#mobile-network-detail').className='mobile-network-detail error';$('#mobile-network-detail').textContent=`Не удалось проверить сеть: ${e.message}`;status.textContent=`Не удалось получить данные: ${e.message}`;return null}}
async function copyMobile(selector,label){const value=$(selector).textContent.trim();if(!value||value.includes('не найден'))return;try{await navigator.clipboard.writeText(value);$('#mobile-status').textContent=`${label} скопирован`}catch{const area=document.createElement('textarea');area.value=value;document.body.append(area);area.select();document.execCommand('copy');area.remove();$('#mobile-status').textContent=`${label} скопирован`}}
$('#copy-mobile-address').onclick=()=>copyMobile('#mobile-address','Адрес');$('#copy-mobile-token').onclick=()=>copyMobile('#mobile-token','Код');$('#refresh-mobile-network').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='Проверяю…';try{await loadMobile()}finally{button.disabled=false;button.textContent='Обновить Wi‑Fi адрес'}};$('#regenerate-mobile-token').onclick=async()=>{if(!confirm('Сменить код? На уже подключённых телефонах понадобится ввести новый.'))return;try{await api('/api/mobile/token/regenerate',{method:'POST'});await loadMobile();$('#mobile-status').textContent='Код изменён. Введи новый код на телефоне.'}catch(e){$('#mobile-status').textContent=e.message}};
let adultPhotoPoll=0;
async function loadVideo(){const el=$('#video-folder-status');try{const v=await api('/api/video');const count=(v.files||[]).length;el.textContent=count?`В папке ${count} видео`:(v.ffmpeg_ready?'Готова принять исходники':'Видеодвижок установится через INSTALL EIRVEN AI.cmd')}catch(e){el.textContent=e.message}}
$('#open-video-folder').onclick=async()=>{const el=$('#video-folder-status');el.textContent='Открываю…';try{const r=await api('/api/video/open',{method:'POST'});el.textContent=r.opened?'Папка video открыта':`Папка: ${r.path}`;setTimeout(loadVideo,500)}catch(e){el.textContent=e.message}};
$('#voice-output-volume').addEventListener('input',e=>$('#voice-output-volume-value').textContent=`${e.target.value}%`);$('#voice-output-volume').addEventListener('change',e=>savePreferences({voice_output_volume:Number(e.target.value)/100}));$('#ui-language').addEventListener('change',e=>savePreferences({language:e.target.value}));$('#autostart-enabled').addEventListener('change',e=>savePreferences({autostart:e.target.checked}));$('#notifications-enabled').addEventListener('change',e=>savePreferences({notifications_enabled:e.target.checked}));$('#mini-mode-enabled').addEventListener('change',e=>savePreferences({mini_mode:e.target.checked}));$('#sphere-motion').addEventListener('change',e=>savePreferences({sphere_motion:e.target.checked}));$('#sphere-intensity').addEventListener('change',e=>savePreferences({sphere_intensity:e.target.value}));$('#desktop-comments-enabled').addEventListener('change',e=>savePreferences({desktop_comments_enabled:e.target.checked}));$('#desktop-eyes-enabled').addEventListener('change',e=>savePreferences({desktop_eyes_enabled:e.target.checked}));$('#update-channel').addEventListener('change',e=>savePreferences({update_channel:e.target.value}));$('#auto-update-check').addEventListener('change',e=>savePreferences({auto_update_check:e.target.checked}));
async function checkUpdates(showErrors=true){const el=$('#update-status'),download=$('#download-update');el.textContent='Проверяю…';download.hidden=true;download.removeAttribute('href');try{const r=await api('/api/updates/check');if(r.ok){if(r.update_available){el.textContent=`Доступно: ${r.latest}`;if(r.asset_url){download.href=r.asset_url;download.textContent=r.asset_name?`Скачать ${r.asset_name}`:'Скачать обновление';download.hidden=false}else if(r.url){download.href=r.url;download.textContent='Открыть релиз';download.hidden=false}}else{el.textContent=`Установлена актуальная версия ${r.current}`}}else el.textContent='Не удалось проверить';return r}catch(e){el.textContent='Не удалось проверить';if(showErrors)addMessage('assistant',`Обновления: ${e.message}`)}}
$('#check-updates').onclick=()=>checkUpdates(true);
$('#shutdown-eirven').onclick=async()=>{if(!confirm('Отключить EIRVEN сейчас?'))return;const b=$('#shutdown-eirven');b.disabled=true;b.textContent='Выключаю…';document.body.classList.add('eirven-shutting-down');try{await api('/api/system/shutdown',{method:'POST'});addMessage('assistant','До встречи. Я выключаюсь.');const started=Date.now();const timer=setInterval(async()=>{try{await api('/api/ping');if(Date.now()-started>4500){clearInterval(timer);b.disabled=false;b.textContent='Повторить отключение';document.body.classList.remove('eirven-shutting-down')}}catch{clearInterval(timer);b.textContent='Отключено';setTimeout(()=>{try{window.close()}catch{}},350)}},250)}catch(e){b.disabled=false;b.textContent='Отключить';document.body.classList.remove('eirven-shutting-down');addMessage('assistant',`Не получилось отключиться: ${e.message}`)}};
$('#clear-current-chat').onclick=async()=>{const id=state.conversationId;if(id){try{await api(`/api/conversations/${id}`,{method:'DELETE'})}catch{}}state.conversationId=null;localStorage.removeItem('eirven_conversation');$('#messages').innerHTML='';await ensureConversation(true);addMessage('assistant','Диалог очищен.');};
function telegramMessage(text,bad=false){const el=$('#telegram-status');el.textContent=String(text||'');el.classList.toggle('error',!!bad)}
async function loadTelegram(){try{const t=await api('/api/telegram');state.telegram=t;$('#telegram-api-id').value=t.config?.api_id||'';$('#telegram-phone').value=t.config?.phone||'';$('#telegram-api-hash').placeholder=t.config?.api_hash_masked?`Сохранён: ${t.config.api_hash_masked}`:'Вставь API Hash';$('#telegram-remote-enabled').checked=!!t.remote?.enabled;$('#telegram-remote-chats').value=(t.remote?.chats||[]).join(', ');$('#telegram-remote-prefix').value=t.remote?.prefix||'Эрви,';const pairing=t.status?.pairing||{};$('#telegram-cancel-pairing').hidden=!pairing.active;telegramMessage(t.status?.message||'Остановлено');return t}catch(e){telegramMessage(e.message,true)}}
$('#telegram-save-config').onclick=async()=>{try{const hash=$('#telegram-api-hash').value.trim();if(!hash)throw new Error('Введи API Hash — маска сохранённого значения не отправляется обратно');await api('/api/telegram/config',{method:'PUT',body:JSON.stringify({api_id:Number($('#telegram-api-id').value),api_hash:hash,phone:$('#telegram-phone').value.trim()})});$('#telegram-api-hash').value='';telegramMessage('Подключение сохранено');await loadTelegram()}catch(e){telegramMessage(e.message,true)}};
$('#telegram-request-code').onclick=async()=>{try{const r=await api('/api/telegram/login/code',{method:'POST'});if(r.user_id&&!$('#telegram-remote-chats').value.trim())$('#telegram-remote-chats').value=r.user_id;if(r.authorized&&r.user_id)telegramMessage(`Telegram уже авторизован. ID аккаунта ${r.user_id} подставлен в «Разрешённые чаты».`);else telegramMessage(r.message||'Код отправлен в Telegram — перенеси его в поле «Код входа»')}catch(e){telegramMessage(e.message,true)}};
$('#telegram-confirm-login').onclick=async()=>{try{const r=await api('/api/telegram/login/confirm',{method:'POST',body:JSON.stringify({code:$('#telegram-login-code').value.trim(),password:$('#telegram-login-password').value})});if(r.user_id&&!$('#telegram-remote-chats').value.trim())$('#telegram-remote-chats').value=r.user_id;$('#telegram-login-password').value='';if(r.requires_password)telegramMessage('Telegram просит пароль двухэтапной защиты — введи его в поле 2FA и нажми «Подтвердить вход» ещё раз');else if(r.authorized&&r.user_id)telegramMessage(`Вход подтверждён. ID аккаунта ${r.user_id} подставлен в «Разрешённые чаты».`);else telegramMessage(r.message||'Вход подтверждён')}catch(e){telegramMessage(e.message,true)}};
$('#telegram-save-remote').onclick=async()=>{try{const chats=$('#telegram-remote-chats').value.split(',').map(x=>x.trim()).filter(Boolean);const r=await api('/api/telegram/remote',{method:'PUT',body:JSON.stringify({enabled:$('#telegram-remote-enabled').checked,chats,prefix:$('#telegram-remote-prefix').value.trim()||'Эрви,'})});telegramMessage(r.remote?.enabled?'Доступ с телефона сохранён':'Удалённые команды выключены')}catch(e){telegramMessage(e.message,true)}};
$('#telegram-monitor-start').onclick=async()=>{try{const r=await api('/api/telegram/start',{method:'POST'});telegramMessage(r.message||'Запускаю Telegram')}catch(e){telegramMessage(e.message,true)}};
$('#telegram-monitor-stop').onclick=async()=>{try{const r=await api('/api/telegram/stop',{method:'POST'});telegramMessage(r.message||'Остановлено')}catch(e){telegramMessage(e.message,true)}};
$('#telegram-pair-chat').onclick=async()=>{try{const r=await api('/api/telegram/pairing/start',{method:'POST'});$('#telegram-cancel-pairing').hidden=false;$('#telegram-pairing-help').textContent=`10 минут: отправь в нужном чате «Эрви, сюда буду отправлять команды». Код для входящего сообщения: ${r.code}`;telegramMessage(r.message||'Ожидаю сообщение из нужного чата')}catch(e){telegramMessage(e.message,true)}};
$('#telegram-cancel-pairing').onclick=async()=>{try{await api('/api/telegram/pairing/cancel',{method:'POST'});$('#telegram-cancel-pairing').hidden=true;$('#telegram-pairing-help').textContent='ID можно не искать и не копировать вручную.';telegramMessage('Привязка отменена')}catch(e){telegramMessage(e.message,true)}};
$('#voice-preview-button').onclick=async e=>{const b=e.currentTarget,old=b.textContent;b.disabled=true;b.textContent='Говорю…';try{const res=await fetch('/api/voice/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:`Привет. Я ${state.identity?.assistant_name||'Эйрвен'}. Говорю спокойно и естественно, как в обычном разговоре.`,emotion:'auto'})});if(!res.ok)throw new Error((await res.text())||'Не удалось получить голос');const blob=await res.blob(),audio=$('#voice-preview');audio.src=URL.createObjectURL(blob);await audio.play()}catch(err){addMessage('assistant',`Голос: ${err.message}`)}finally{b.textContent=old;b.disabled=false}};

async function loadTasks(){const box=$('#task-list');try{const tasks=await api('/api/tasks?limit=30');box.innerHTML='';const visible=(tasks||[]).filter(t=>!['cancelled'].includes(String(t.status||'')));if(!visible.length){box.innerHTML=`<div class="task-card"><h3>Сейчас спокойно</h3><p>Когда ${escapeHtml(configuredName())} начнёт длинную задачу, прогресс появится здесь.</p></div>`;return}visible.forEach(t=>{const card=document.createElement('div');card.className='task-card';const progress=Math.round((Number(t.progress)||0)*100);card.innerHTML=`<div class="task-top"><h3>${escapeHtml(t.title||t.kind||'Задача')}</h3><small>${escapeHtml(t.status||'')}</small></div><p>${escapeHtml(t.current_step||'')}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,progress))}%"></i></div>`;box.append(card)})}catch(e){box.innerHTML=`<div class="task-card"><h3>Не удалось загрузить задачи</h3><p>${escapeHtml(e.message)}. Нажми «Задачи» ещё раз, чтобы повторить.</p></div>`}}
setInterval(()=>{if(state.view==='tasks')loadTasks()},1600);
$('#main-orb').onclick=()=>{if(state.runtime.onboarding_complete===false){openOnboarding();return}if(state.runtime.session_active)$('#message-input').focus();else{const el=$('#voice-state');el.textContent=`скажи «${wakeName()}» — я засвечусь`;setTimeout(()=>pollRuntime(),1500)}};

let onboardingDraft={style:'balanced'};
function showOnboardStep(n){$$('.onboarding-step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===n));$$('.onboarding-dots i').forEach((d,i)=>d.classList.toggle('active',i===n-1))}
function openOnboarding(){document.body.classList.add('onboarding-open');$('#onboarding').setAttribute('aria-hidden','false');showOnboardStep(1)}
function closeOnboarding(){document.body.classList.remove('onboarding-open');$('#onboarding').setAttribute('aria-hidden','true')}
$$('.onboard-next').forEach(b=>b.onclick=()=>{const next=Number(b.dataset.next);if(next===2){onboardingDraft.assistant_name=$('#onboard-assistant-name').value.trim()||'Эйрвен';onboardingDraft.style=onboardingDraft.style||presetFromStyle(state.style)||'balanced';setPresetButtons($('#onboard-style'),onboardingDraft.style);$('#onboard-wake-name').textContent=onboardingDraft.assistant_name}if(next===3){const name=$('#onboard-user-name').value.trim();if(!name){$('#onboard-user-name').focus();return}onboardingDraft.user_address=name;$('#onboard-wake-name').textContent=onboardingDraft.assistant_name||configuredName();const phrases=[`Какое красивое имя, ${name}. Приятно познакомиться.`,`${name}, отлично. Теперь мы знакомы.`,`Приятно познакомиться, ${name}. Я рядом.`];$('#onboard-greeting').textContent=phrases[Math.floor(Math.random()*phrases.length)]}showOnboardStep(next)});
$('#finish-onboarding').onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Запускаю…';try{await saveIdentity({assistant_name:onboardingDraft.assistant_name||$('#onboard-assistant-name').value.trim()||'Эйрвен',user_address:onboardingDraft.user_address||$('#onboard-user-name').value.trim(),onboarding_completed:true});await saveStylePreset(onboardingDraft.style||'balanced');try{await api('/api/voice/runtime/restart',{method:'POST'})}catch{}closeOnboarding();addMessage('assistant',`Я здесь. Скажи «${configuredName()}», когда понадоблюсь.`);pollRuntime()}catch(err){b.textContent='Попробовать ещё';addMessage('assistant',`Запуск: ${err.message}`)}finally{b.disabled=false}};

(async function init(){try{await loadIdentity();await ensureConversation();await loadHistory();await loadStyle();await loadPreferences();loadTasks();onboardingDraft.style=presetFromStyle(state.style);if(!state.identity?.onboarding_completed||new URLSearchParams(location.search).get('welcome')==='1')openOnboarding()}catch(e){addMessage('assistant',`Запуск интерфейса: ${e.message}`)}})();
