const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const state={identity:null,style:null,preferences:null,runtime:{},conversationId:localStorage.getItem('eirven_conversation')||null,job:null,view:'home',runtimeAction:{}};
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok){let t=await r.text();try{t=JSON.parse(t).detail||t}catch{}throw new Error(t||`HTTP ${r.status}`)}const ct=r.headers.get('content-type')||'';return ct.includes('application/json')?r.json():r.text()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function configuredName(){return String(state.identity?.assistant_name||'Эйрвен').trim()||'Эйрвен'}
function wakeName(r=state.runtime){return String(r?.wake_phrase||configuredName()).trim()||configuredName()}
function applyAssistantName(raw){const name=String(raw||'Эйрвен').trim()||'Эйрвен';document.title=name;$$('.assistant-name-ref').forEach(el=>el.textContent=name);$('#stage-title').textContent=state.view==='home'?name:$('#stage-title').textContent;$('.brand-orb').title=name;$('.brand-orb').setAttribute('aria-label',name);$('#main-orb').setAttribute('aria-label',`Сфера ${name}`);$('#message-input').placeholder=`Напиши ${name}…`;$('#home-wake-name').textContent=name;$('#onboard-wake-name').textContent=name;$('#onboard-intro-name').textContent=name}
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#stage-title').textContent=name==='home'?(state.identity?.assistant_name||'Эйрвен'):{tasks:'Задачи',settings:'Настройки'}[name]||'Эйрвен';if(name==='tasks')loadTasks();if(name==='settings')loadPreferences()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
function addMessage(role,text,extra=''){const box=$('#messages'),node=document.createElement('div');node.className=`message ${role} ${extra}`;node.textContent=text;box.append(node);box.scrollTop=box.scrollHeight;return node}
async function ensureConversation(force=false){if(state.conversationId&&!force)return state.conversationId;const conv=await api('/api/conversations',{method:'POST',body:JSON.stringify({title:configuredName(),mode:'Друг'})});state.conversationId=conv.id;localStorage.setItem('eirven_conversation',state.conversationId);return state.conversationId}
async function loadHistory(){if(!state.conversationId)return;try{const conv=await api(`/api/conversations/${state.conversationId}`);$('#messages').innerHTML='';(conv.messages||[]).slice(-50).forEach(m=>addMessage(m.role==='user'?'user':'assistant',m.content||''))}catch{state.conversationId=null;localStorage.removeItem('eirven_conversation')}}
function autosize(){const input=$('#message-input');input.style.height='auto';input.style.height=`${Math.min(180,Math.max(76,input.scrollHeight))}px`}
async function streamChat(payload,node){const response=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error((await response.text())||`HTTP ${response.status}`);if(!response.body)throw new Error('Поток ответа недоступен');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',full='';for(;;){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let split;while((split=buffer.indexOf('\n\n'))>=0){const packet=buffer.slice(0,split);buffer=buffer.slice(split+2);for(const line of packet.split('\n')){if(!line.startsWith('data:'))continue;let event;try{event=JSON.parse(line.slice(5).trim())}catch{continue}if(event.type==='token'){full=event.full||full+(event.content||'');node.textContent=full;node.classList.remove('pending')}else if(event.type==='error')throw new Error(event.message||'Ошибка модели');else if(event.type==='done'){full=event.answer||full;node.textContent=full||'Готово.';node.classList.remove('pending')}}}}node.classList.remove('pending');return full}
async function sendMessage(){const input=$('#message-input'),message=input.value.trim();if(!message)return;await ensureConversation();input.value='';autosize();addMessage('user',message);const pending=addMessage('assistant','…','pending');try{await streamChat({message,conversation_id:state.conversationId,mode:'Друг',model:'auto',attachment_ids:[]},pending)}catch(e){pending.classList.remove('pending');pending.textContent=`Ошибка: ${e.message}`}}
$('#send-message').onclick=sendMessage;$('#message-input').addEventListener('input',autosize);$('#message-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});$('#new-chat').onclick=async()=>{state.conversationId=null;localStorage.removeItem('eirven_conversation');$('#messages').innerHTML='';await ensureConversation(true)};

function runtimeLabel(r){if(r.onboarding_complete===false||r.state==='onboarding')return 'знакомлюсь с тобой';if(r.error)return 'микрофон недоступен';if(r.state==='warming'||r.interactive_ready===false)return 'запускаюсь';if(r.speaking)return 'говорю';if(r.state==='hearing')return 'слушаю';if(r.state==='recognizing')return 'понимаю';if(r.state==='thinking')return 'думаю';if(r.state==='armed'||r.session_active)return 'слушаю — говори';return `скажи «${wakeName(r)}»`}
function updateOrb(r){const orb=$('#main-orb');['active','hearing','speaking','thinking','onboarding'].forEach(c=>orb.classList.remove(c));if(r.onboarding_complete===false||r.state==='onboarding')orb.classList.add('onboarding');if(r.session_active||r.state==='armed')orb.classList.add('active');if(r.state==='hearing'||r.state==='recognizing')orb.classList.add('hearing');if(r.state==='thinking')orb.classList.add('thinking');if(r.speaking)orb.classList.add('speaking');const level=Math.min(.22,Number(r.input_level)||0);document.documentElement.style.setProperty('--voice-level',String(level));document.documentElement.style.setProperty('--arm',String(Math.max(0,Math.min(1,(Number(r.session_seconds_remaining)||0)/5))))}
async function pollRuntime(){try{const r=await api('/api/voice/runtime');state.runtime=r;updateOrb(r);const wake=wakeName(r);$('#home-wake-name').textContent=wake;$('#onboard-wake-name').textContent=wake;const label=runtimeLabel(r);$('#voice-state').textContent=label;$('#heard-text').textContent=['hearing','recognizing','thinking'].includes(r.state)?(r.last_text||''):'';const chip=$('#runtime-chip');chip.className='runtime-chip '+(r.error?'error':(r.speaking||r.session_active||['hearing','recognizing','thinking','armed'].includes(r.state))?'active':r.running?'live':'');chip.querySelector('b').textContent=label;$('#health-dot').className='health-dot '+(r.running&&!r.error?'ok':'bad')}catch{$('#health-dot').className='health-dot bad'}}
setInterval(pollRuntime,150);pollRuntime();

function humanActivity(rt){if(!rt||!rt.cancellable)return'';let step=String(rt.step||rt.action||'').trim(),goal=String(rt.goal||'').trim();if(step&&!["готово","idle","остановлено"].includes(step.toLowerCase()))return step.replace(/\.$/,'')+'…';if(goal)return 'Занимаюсь: '+goal.slice(0,90)+(goal.length>90?'…':'');return''}
async function pollAction(){try{const rt=await api('/api/runtime');state.runtimeAction=rt;const text=humanActivity(rt),el=$('#activity-caption');el.textContent=text;el.classList.toggle('visible',!!text)}catch{}}
setInterval(pollAction,500);pollAction();

const STYLE_PRESETS={balanced:{directness:4,humor:'сухой, ироничный, без клоунады',emotional_support:true,answer_length:'средняя',custom_rules:'Говори естественно, без канцелярита. Подстраивай тон и длину ответа под ситуацию.'},friendly:{directness:3,humor:'лёгкий дружеский юмор',emotional_support:true,answer_length:'средняя',custom_rules:'Говори тепло, естественно и живо. Не будь приторной и не повторяй запрос.'},brief:{directness:5,humor:'без юмора',emotional_support:false,answer_length:'короткая',custom_rules:'Отвечай коротко и конкретно. Не проговаривай очевидные шаги и не используй канцелярит.'},free:{directness:4,humor:'игривый, живой, но не навязчивый',emotional_support:true,answer_length:'средняя',custom_rules:'Говори свободно и по-человечески, допускай короткие шутки, но не превращай ответы в шоу.'}};
function presetFromStyle(st){const h=String(st?.humor||'');if(st?.answer_length==='короткая'||Number(st?.directness)>=5)return'brief';if(h.includes('игрив'))return'free';if(h.includes('друж'))return'friendly';return'balanced'}
async function saveStylePreset(name){const current=await api('/api/style');const patch=STYLE_PRESETS[name]||STYLE_PRESETS.balanced;state.style=await api('/api/style',{method:'PUT',body:JSON.stringify({...current,...patch,assistant_name:state.identity?.assistant_name||current.assistant_name,owner_name:state.identity?.user_address||current.owner_name})});$('#communication-style').value=name}
async function loadIdentity(){const id=await api('/api/identity');state.identity=id;$('#assistant-name').value=id.assistant_name||'Эйрвен';$('#user-address').value=id.user_address||'';$('#onboard-assistant-name').value=id.assistant_name||'Эйрвен';$('#onboard-user-name').value=id.user_address||'';applyAssistantName(id.assistant_name);return id}
async function saveIdentity(patch){const id=await api('/api/identity',{method:'PUT',body:JSON.stringify(patch)});state.identity=id;await loadIdentity();return id}
async function loadStyle(){try{state.style=await api('/api/style');$('#communication-style').value=presetFromStyle(state.style);$('#onboard-style').value=presetFromStyle(state.style)}catch{}}
$('#assistant-name').addEventListener('change',e=>saveIdentity({assistant_name:e.target.value}));$('#user-address').addEventListener('change',e=>saveIdentity({user_address:e.target.value}));$('#communication-style').addEventListener('change',e=>saveStylePreset(e.target.value));

function applyAppearance(p={}){document.body.classList.toggle('sphere-motion-off',p.sphere_motion===false);document.body.classList.remove('sphere-soft','sphere-balanced','sphere-vivid');document.body.classList.add(`sphere-${p.sphere_intensity||'vivid'}`)}
async function loadPreferences(){try{const p=await api('/api/preferences');state.preferences=p;$('#voice-output-volume').value=Math.round(Number(p.voice_output_volume??.82)*100);$('#voice-output-volume-value').textContent=`${$('#voice-output-volume').value}%`;$('#ui-language').value=p.language||'ru';$('#autostart-enabled').checked=!!p.autostart;$('#notifications-enabled').checked=p.notifications_enabled!==false;$('#mini-mode-enabled').checked=p.mini_mode!==false;$('#sphere-motion').checked=p.sphere_motion!==false;$('#sphere-intensity').value=p.sphere_intensity||'vivid';$('#desktop-comments-enabled').checked=p.desktop_comments_enabled!==false;$('#desktop-eyes-enabled').checked=p.desktop_eyes_enabled!==false;$('#update-channel').value=p.update_channel||'stable';$('#auto-update-check').checked=p.auto_update_check!==false;$('#version-caption').textContent=`EIRVEN ${p.version||'1.2.2'} · ${p.build||'r22.4-send-icon-favicon-hotfix'}`;$('#version-pill').textContent=p.build||'r22.4-send-icon-favicon-hotfix';applyAppearance(p);return p}catch(e){return null}}
async function savePreferences(patch){try{const p=await api('/api/preferences',{method:'PUT',body:JSON.stringify(patch)});state.preferences=p;applyAppearance(p);return p}catch(e){addMessage('assistant',`Настройки: ${e.message}`);throw e}}
$$('[data-settings-tab]').forEach(b=>b.onclick=()=>{$$('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-settings-panel]').forEach(x=>x.classList.toggle('active',x.dataset.settingsPanel===b.dataset.settingsTab));if(b.dataset.settingsTab==='updates'&&state.preferences?.auto_update_check)checkUpdates(false)});
$('#voice-output-volume').addEventListener('input',e=>$('#voice-output-volume-value').textContent=`${e.target.value}%`);$('#voice-output-volume').addEventListener('change',e=>savePreferences({voice_output_volume:Number(e.target.value)/100}));$('#ui-language').addEventListener('change',e=>savePreferences({language:e.target.value}));$('#autostart-enabled').addEventListener('change',e=>savePreferences({autostart:e.target.checked}));$('#notifications-enabled').addEventListener('change',e=>savePreferences({notifications_enabled:e.target.checked}));$('#mini-mode-enabled').addEventListener('change',e=>savePreferences({mini_mode:e.target.checked}));$('#sphere-motion').addEventListener('change',e=>savePreferences({sphere_motion:e.target.checked}));$('#sphere-intensity').addEventListener('change',e=>savePreferences({sphere_intensity:e.target.value}));$('#desktop-comments-enabled').addEventListener('change',e=>savePreferences({desktop_comments_enabled:e.target.checked}));$('#desktop-eyes-enabled').addEventListener('change',e=>savePreferences({desktop_eyes_enabled:e.target.checked}));$('#update-channel').addEventListener('change',e=>savePreferences({update_channel:e.target.value}));$('#auto-update-check').addEventListener('change',e=>savePreferences({auto_update_check:e.target.checked}));
async function checkUpdates(showErrors=true){const el=$('#update-status'),download=$('#download-update');el.textContent='Проверяю…';download.hidden=true;download.removeAttribute('href');try{const r=await api('/api/updates/check');if(r.ok){if(r.update_available){el.textContent=`Доступно: ${r.latest}`;if(r.asset_url){download.href=r.asset_url;download.textContent=r.asset_name?`Скачать ${r.asset_name}`:'Скачать обновление';download.hidden=false}else if(r.url){download.href=r.url;download.textContent='Открыть релиз';download.hidden=false}}else{el.textContent=`Установлена актуальная версия ${r.current}`}}else el.textContent='Не удалось проверить';return r}catch(e){el.textContent='Не удалось проверить';if(showErrors)addMessage('assistant',`Обновления: ${e.message}`)}}
$('#check-updates').onclick=()=>checkUpdates(true);
$('#shutdown-eirven').onclick=async()=>{if(!confirm('Отключить EIRVEN сейчас?'))return;const b=$('#shutdown-eirven');b.disabled=true;b.textContent='Выключаю…';document.body.classList.add('eirven-shutting-down');try{await api('/api/system/shutdown',{method:'POST'});addMessage('assistant','До встречи. Я выключаюсь.');const started=Date.now();const timer=setInterval(async()=>{try{await api('/api/ping');if(Date.now()-started>4500){clearInterval(timer);b.disabled=false;b.textContent='Повторить отключение';document.body.classList.remove('eirven-shutting-down')}}catch{clearInterval(timer);b.textContent='Отключено';setTimeout(()=>{try{window.close()}catch{}},350)}},250)}catch(e){b.disabled=false;b.textContent='Отключить';document.body.classList.remove('eirven-shutting-down');addMessage('assistant',`Не получилось отключиться: ${e.message}`)}};
$('#clear-current-chat').onclick=async()=>{const id=state.conversationId;if(id){try{await api(`/api/conversations/${id}`,{method:'DELETE'})}catch{}}state.conversationId=null;localStorage.removeItem('eirven_conversation');$('#messages').innerHTML='';await ensureConversation(true);addMessage('assistant','Диалог очищен.');};
$('#voice-preview-button').onclick=async e=>{const b=e.currentTarget,old=b.textContent;b.disabled=true;b.textContent='Говорю…';try{const res=await fetch('/api/voice/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:`Привет. Я ${state.identity?.assistant_name||'Эйрвен'}. Говорю спокойно и естественно, как в обычном разговоре.`,emotion:'auto'})});if(!res.ok)throw new Error((await res.text())||'Не удалось получить голос');const blob=await res.blob(),audio=$('#voice-preview');audio.src=URL.createObjectURL(blob);await audio.play()}catch(err){addMessage('assistant',`Голос: ${err.message}`)}finally{b.textContent=old;b.disabled=false}};

async function loadTasks(){try{const tasks=await api('/api/tasks?limit=30'),box=$('#task-list');box.innerHTML='';const visible=(tasks||[]).filter(t=>!['cancelled'].includes(String(t.status||'')));if(!visible.length){box.innerHTML=`<div class="task-card"><h3>Сейчас спокойно</h3><p>Когда ${escapeHtml(configuredName())} начнёт длинную задачу, прогресс появится здесь.</p></div>`;return}visible.forEach(t=>{const card=document.createElement('div');card.className='task-card';const progress=Math.round((Number(t.progress)||0)*100);card.innerHTML=`<div class="task-top"><h3>${escapeHtml(t.title||t.kind||'Задача')}</h3><small>${escapeHtml(t.status||'')}</small></div><p>${escapeHtml(t.current_step||'')}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,progress))}%"></i></div>`;box.append(card)})}catch{}}
setInterval(()=>{if(state.view==='tasks')loadTasks()},1600);
$('#main-orb').onclick=()=>{if(state.runtime.onboarding_complete===false){openOnboarding();return}if(state.runtime.session_active)$('#message-input').focus();else{const el=$('#voice-state');el.textContent=`скажи «${wakeName()}» — я засвечусь`;setTimeout(()=>pollRuntime(),1500)}};

let onboardingDraft={style:'balanced'};
function showOnboardStep(n){$$('.onboarding-step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===n));$$('.onboarding-dots i').forEach((d,i)=>d.classList.toggle('active',i===n-1))}
function openOnboarding(){document.body.classList.add('onboarding-open');$('#onboarding').setAttribute('aria-hidden','false');showOnboardStep(1)}
function closeOnboarding(){document.body.classList.remove('onboarding-open');$('#onboarding').setAttribute('aria-hidden','true')}
$$('.onboard-next').forEach(b=>b.onclick=()=>{const next=Number(b.dataset.next);if(next===2){onboardingDraft.assistant_name=$('#onboard-assistant-name').value.trim()||'Эйрвен';onboardingDraft.style=$('#onboard-style').value||'balanced';$('#onboard-wake-name').textContent=onboardingDraft.assistant_name}if(next===3){const name=$('#onboard-user-name').value.trim();if(!name){$('#onboard-user-name').focus();return}onboardingDraft.user_address=name;$('#onboard-wake-name').textContent=onboardingDraft.assistant_name||configuredName();const phrases=[`Какое красивое имя, ${name}. Приятно познакомиться.`,`${name}, отлично. Теперь мы знакомы.`,`Приятно познакомиться, ${name}. Я рядом.`];$('#onboard-greeting').textContent=phrases[Math.floor(Math.random()*phrases.length)]}showOnboardStep(next)});
$('#finish-onboarding').onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Запускаю…';try{await saveIdentity({assistant_name:onboardingDraft.assistant_name||$('#onboard-assistant-name').value.trim()||'Эйрвен',user_address:onboardingDraft.user_address||$('#onboard-user-name').value.trim(),onboarding_completed:true});await saveStylePreset(onboardingDraft.style||'balanced');try{await api('/api/voice/runtime/restart',{method:'POST'})}catch{}closeOnboarding();addMessage('assistant',`Я здесь. Скажи «${configuredName()}», когда понадоблюсь.`);pollRuntime()}catch(err){b.textContent='Попробовать ещё';addMessage('assistant',`Запуск: ${err.message}`)}finally{b.disabled=false}};

(async function init(){try{await loadIdentity();await ensureConversation();await loadHistory();await loadStyle();await loadPreferences();loadTasks();onboardingDraft.style=presetFromStyle(state.style);if(!state.identity?.onboarding_completed||new URLSearchParams(location.search).get('welcome')==='1')openOnboarding()}catch(e){addMessage('assistant',`Запуск интерфейса: ${e.message}`)}})();
