name: Feature request
description: Предложить новую возможность EIRVEN
title: "[Idea] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую реальную задачу это решает?
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Как это должно выглядеть для пользователя?
    validations:
      required: true
